- name: default
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible')}}"
  hosts: localhost
  # vars:
  #   Course: "Java"

- name: lower case
  hosts: localhost
  vars:
    Wishes: Hello Good
  tasks:
  - name: Lower case
    ansible.builtin.debug:
      msg: "Hi, {{Wishes | lower}}"

- name: Upper case
  hosts: localhost
  vars:
    Wishes: Hello Good
  tasks:
  - name: Lower case
    ansible.builtin.debug:
      msg: "Hi, {{Wishes | upper}}"