- name: default
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible')}}"
  hosts: localhost
  # vars:
  #   Course: "Java"

- name: lower case
  hosts: localhost
  vars:
    Wishes: Hello Good
  tasks:
  - name: Lower case
    ansible.builtin.debug:
      msg: "Hi, {{Wishes | lower}}"

- name: Upper case
  hosts: localhost
  vars:
    Wishes: Hello Good
  tasks:
  - name: Lower case
    ansible.builtin.debug:
      msg: "Hi, {{Wishes | upper}}"

- name: remove duplicates
  hosts: localhost
  vars:
    Lists:
    - sai
    - sai
    - krishna
  tasks:
  - name: remove duplicates1
    ansible.builtin.debug:
      msg: "Remove {{Lists | unique}}"

- name: print min and max values
  hosts: localhost
  vars:
    ages: [12,3,4,55,66]
  tasks:
  - name: print min and max values
    ansible.builtin.debug:
      msg: 
        - "Given values are {{ ages }}"
        - "Max value is {{ ages | max }} and Min value is {{ ages | min }}"