172.31.40.204
[web]

[db]

[backend]

; [localhost]
; localhost

; [localhost:vars]
; Course="Terraform-inventory"
; Trainer="deva"
; Duration="2hrs"

[all:children]
#web
db
backend

[defaults]
stdout_callback = yaml
bin_ansible_callbacks = True