- name: variable preference
  hosts: localhost
  #connection: local
  vars:
    # Course: "Terraform-vars"
    # Trainer: "deva"
    # Duration: "120 hrs"
  vars_files:
  # - vars.yml
  vars_prompt:
  - name: Course
    prompt: Please enter your course
    private: false
  tasks:
  - name: print information
    # vars:
    #   Course: "Terraform-override"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}}"