- name: Remove ansible & nginx
  hosts: web
  tasks:
  - name: Remove ansible
    ansible.builtin.dnf:
      name: ansible
      state: absent
  - name: Remove nginx
    ansible.builtin.dnf:
      name: nginx
      state: absent
