- name: variables
  vars:
    Course: "Devops"
    Trainer: "sai"
    Duration: "2hrs"
  hosts: localhost
  tasks:
  - name: print information
    # vars:
    #   Course: "Terraform"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, duration is {{Duration}}"