- name: variable from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your USERNAME
    private: false
  - name: PASSWORD
    prompt: Please enter your PASSWORD
    private: true
  tasks:
  - name: print information
    ansible.builtin.debug:
    msg: "Hi, Username: {{USERNAME}}, Password: {{PASSWORD}}"